Update installation with npm
witheve/docs pull request #52
Opened 2016-12-08 00:07 UTC by cmontella

2016-12-08 00:08 UTC, cmontella commented
Fixes https://github.com/witheve/docs/issues/51

2016-12-08 02:06 UTC, joshuafcole requested changes

2016-12-08 02:06 UTC, joshuafcole commented on handbook/running.md
> +## Running Eve in Serve mode
Server*

2016-12-08 02:06 UTC, joshuafcole commented on handbook/running.md
> +Without this flag, execution of Eve programs happens within the browser, with the Eve server acting as an intermediary between the browser and your local system. In server mode, Eve will instead exec
acting *only* as an file server.

2016-12-13 00:52 UTC, joshuafcole approved these changes

2016-12-13 00:52 UTC, merged